import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
   "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.bold]
family = "MesloLGL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font Mono"
style = "Regular"


[window]
opacity = 0.97
dimensions = { columns = 107, lines = 37 }

[mouse]
hide_when_typing = true
